/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorFichapaciente;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author aleja
 */
public class VentanaFichapacientes extends javax.swing.JFrame {

    /**
     * Creates new form VentanaFichapacientes
     */
    public VentanaFichapacientes() {
        initComponents();
        txtAreavisita.setLineWrap(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Stock = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFknumpa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNompa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablevisitas = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFechavisita = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreavisita = new javax.swing.JTextArea();
        btnAgregarar = new javax.swing.JButton();
        btnModificarar = new javax.swing.JButton();
        btnEliminarar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNumvisita = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Stock.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("PACIENTE N°:");

        txtFknumpa.setEditable(false);
        txtFknumpa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("NOMBRE:");

        txtNompa.setEditable(false);
        txtNompa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jtablevisitas = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        jtablevisitas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtablevisitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "FECHA", "VISITA"
            }
        ));
        jtablevisitas.setFocusable(false);
        jtablevisitas.getTableHeader().setResizingAllowed(false);
        jtablevisitas.getTableHeader().setReorderingAllowed(false);
        jtablevisitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablevisitasMouseClicked(evt);
            }
        });
        jtablevisitas.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jtablevisitasComponentHidden(evt);
            }
        });
        jtablevisitas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtablevisitasKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtablevisitas);
        if (jtablevisitas.getColumnModel().getColumnCount() > 0) {
            jtablevisitas.getColumnModel().getColumn(0).setMaxWidth(50);
            jtablevisitas.getColumnModel().getColumn(1).setMinWidth(100);
            jtablevisitas.getColumnModel().getColumn(1).setPreferredWidth(100);
            jtablevisitas.getColumnModel().getColumn(1).setMaxWidth(100);
            jtablevisitas.getColumnModel().getColumn(2).setPreferredWidth(100);
            jtablevisitas.getColumnModel().getColumn(2).setMaxWidth(350);
        }

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("VISITA:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("FECHA:");

        txtFechavisita.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtAreavisita.setColumns(20);
        txtAreavisita.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAreavisita.setRows(5);
        jScrollPane2.setViewportView(txtAreavisita);

        btnAgregarar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disket.png"))); // NOI18N
        btnAgregarar.setText("AGREGAR");
        btnAgregarar.setBorder(new javax.swing.border.MatteBorder(null));
        btnAgregarar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregararActionPerformed(evt);
            }
        });

        btnModificarar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lapiz.png"))); // NOI18N
        btnModificarar.setText("MODIFICAR");
        btnModificarar.setBorder(new javax.swing.border.MatteBorder(null));
        btnModificarar.setMaximumSize(new java.awt.Dimension(75, 35));
        btnModificarar.setMinimumSize(new java.awt.Dimension(75, 35));
        btnModificarar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificararActionPerformed(evt);
            }
        });

        btnEliminarar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/basura.png"))); // NOI18N
        btnEliminarar.setText("ELIMINAR");
        btnEliminarar.setBorder(new javax.swing.border.MatteBorder(null));
        btnEliminarar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminararActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("VISITA N°:");

        txtNumvisita.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3792081-broom-halloween-magic-witch_109049.png"))); // NOI18N
        btnLimpiar.setBorder(new javax.swing.border.MatteBorder(null));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StockLayout = new javax.swing.GroupLayout(Stock);
        Stock.setLayout(StockLayout);
        StockLayout.setHorizontalGroup(
            StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StockLayout.createSequentialGroup()
                        .addGroup(StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(StockLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFknumpa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StockLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumvisita, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StockLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNompa, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StockLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechavisita, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar))))
                    .addGroup(StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addGroup(StockLayout.createSequentialGroup()
                                .addComponent(btnAgregarar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btnModificarar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btnEliminarar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        StockLayout.setVerticalGroup(
            StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StockLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(StockLayout.createSequentialGroup()
                        .addGroup(StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFknumpa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtNompa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtFechavisita, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumvisita, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregararActionPerformed
        // TODO add your handling code here:
        ControladorFichapaciente.botonAgregar();

    }//GEN-LAST:event_btnAgregararActionPerformed

    private void btnModificararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificararActionPerformed
        // TODO add your handling code here:
        ControladorFichapaciente.botonModificar();
    }//GEN-LAST:event_btnModificararActionPerformed

    private void btnEliminararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminararActionPerformed
        ControladorFichapaciente.botonEliminar();
    }//GEN-LAST:event_btnEliminararActionPerformed

    private void jtablevisitasComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jtablevisitasComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jtablevisitasComponentHidden

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        ControladorFichapaciente.limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jtablevisitasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtablevisitasKeyReleased
        // TODO add your handling code here:
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_UP)) {
            int seleccion = jtablevisitas.getSelectedRow();
            txtNumvisita.setText(String.valueOf(jtablevisitas.getValueAt(seleccion, 0)));
            txtFechavisita.setText(String.valueOf(jtablevisitas.getValueAt(seleccion, 1)));
            txtAreavisita.setText(String.valueOf(jtablevisitas.getValueAt(seleccion, 2)));
        }
    }//GEN-LAST:event_jtablevisitasKeyReleased

    private void jtablevisitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablevisitasMouseClicked
        // TODO add your handling code here:
        int seleccion = jtablevisitas.getSelectedRow();
            txtNumvisita.setText(String.valueOf(jtablevisitas.getValueAt(seleccion, 0)));
            txtFechavisita.setText(String.valueOf(jtablevisitas.getValueAt(seleccion, 1)));
            txtAreavisita.setText(String.valueOf(jtablevisitas.getValueAt(seleccion, 2)));
    }//GEN-LAST:event_jtablevisitasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFichapacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFichapacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFichapacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFichapacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFichapacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Stock;
    public javax.swing.JButton btnAgregarar;
    public javax.swing.JButton btnEliminarar;
    private javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnModificarar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtablevisitas;
    private javax.swing.JTextArea txtAreavisita;
    private javax.swing.JTextField txtFechavisita;
    private javax.swing.JTextField txtFknumpa;
    private javax.swing.JTextField txtNompa;
    private javax.swing.JTextField txtNumvisita;
    // End of variables declaration//GEN-END:variables
    public JTable getJtbVisitas() {
        jtablevisitas.setRowHeight(60);
        DefaultTableCellRenderer centrartextocolumna = new DefaultTableCellRenderer();
        DefaultTableCellRenderer arribafila = new DefaultTableCellRenderer();
        centrartextocolumna.setHorizontalAlignment(SwingConstants.CENTER);
        arribafila.setVerticalAlignment(SwingConstants.TOP);
        jtablevisitas.getColumnModel().getColumn(0).setCellRenderer(centrartextocolumna);
        jtablevisitas.getColumnModel().getColumn(1).setCellRenderer(centrartextocolumna);
        jtablevisitas.getColumnModel().getColumn(2).setCellRenderer(arribafila);
        return jtablevisitas;
    }

    public JTextArea getTxtAreavisita() {
        return txtAreavisita;
    }

    public JTextField getTxtFechavisita() {
        return txtFechavisita;
    }

    public JTextField getTxtFknumpa() {
        txtFknumpa.setHorizontalAlignment(SwingConstants.CENTER);
        return txtFknumpa;
    }

    public JTextField getTxtNompa() {
        return txtNompa;
    }

    public JTextField getTxtNumvisita() {
        txtNumvisita.setHorizontalAlignment(SwingConstants.CENTER);
        return txtNumvisita;
    }

}
